GPUS : '0'
PRINT_FREQ : 200
SAVE_EVERY_EPOCH : 50
ADD_TIMESTAMP : False

OUTPUT_DIR : '/cvlabdata2/home/davydov/videoHMR_SSL/output/ft_w_coco_seqlen2_normOFloss_OFonHR'

MODELS :
  hmrnet :
    DIR : 'hmr'
    ARCH : 'get_hmr'
    PARAMS :
      pretrained : True

LOSSES : 
  ### old EFT part 
  smpl_pose_loss :
    DIR : 'train_hmr'
    NAME : 'SmplPoseLoss'
    WEIGHT : 1.
  smpl_shape_loss :
    DIR : 'train_hmr'
    NAME : 'SmplShapeLoss'
    WEIGHT : 0.001
  smpl_shape_prior_loss :
    DIR : 'train_hmr'
    NAME : 'SmplShapePriorLoss'
    WEIGHT : 1.
  kpts2d_loss :
    DIR : 'train_hmr'
    NAME : 'Kpts2dLoss'
    WEIGHT : 5.
  kpts3d_loss :
    DIR : 'train_hmr'
    NAME : 'Kpts3dLoss'
    WEIGHT : 5.
  camera_scale_reg_loss :
    DIR : 'train_hmr'
    NAME : 'CameraScaleRegLoss'
    WEIGHT : 1.

  ### new OFC guided part
  flow_2d :
    DIR : 'optical_flow'
    NAME : 'Flow2DLoss'
    PARAMS : 
      normalize_OF : True
      do_thresholding : True
    WEIGHT : 1.

  ### these are the trackers mostly
  pose2d :
    DIR : 'pose_eval'
    NAME : 'Keypoint2DPixelAlignment'

  mpjpe :
    DIR : 'pose_eval'
    NAME : 'MPJPE'
  pa_mpjpe :
    DIR : 'pose_eval'
    NAME : 'PAMPJPE'
  mpvpe :
    DIR : 'pose_eval'
    NAME : 'MPVPE'
  accel :
    DIR : 'pose_eval'
    NAME : 'Acceleration'
  accel_err :
    DIR : 'pose_eval'
    NAME : 'AccelerationError'

OPTIM :
  hmrnet :
    NAME : 'Adam'
    PARAMS :
      lr : 0.00001
      betas : [0.5, 0.999]
      weight_decay : 0

DATASETS :
  train_frame :
    DIR : 'coco_eft'
    NAME : 'COCO_EFT'
  train_video :
    DIR : 'threedpw'
    NAME : 'ThreeDPW'
    PARAMS :
      set : "test" # "train" - to see an improvement on the test set! 
      seqlen : 2
      debug : True
      use_OFformat : True

  eval :
    DIR : 'threedpw'
    NAME : 'ThreeDPW'
    PARAMS :
      set : "test"
      seqlen : 16
      debug : True

DATALOAD :
  train_frame :
    PARAMS :
      shuffle : True
      batch_size : 16 
      num_workers : 8
  train_video :
    PARAMS :
      shuffle : True
      batch_size : 16
      num_workers : 8
  multidl : 
      dls : ["train_frame", "train_video"]
      NUM_ITERATIONS_PER_EPOCH : 1000
  eval :
    PARAMS :
      shuffle : False
      batch_size : 1
      num_workers : 16

TRAINING :
  END_EPOCH : 100
  RESUME :
    CKPT : "/cvlabdata2/home/davydov/videoHMR_SSL/eft_model_zoo/coco-all.pt"
    LOAD_MODELS_ONLY : True


PROCEDURE : 'finetune_hmr_ssl_w_single_frame_gt_seqlen2_OFonHR'

W_FRAME : 1.
W_OFC : 0.01

EXP_NAME : 'ft_w_coco__3dpw_test__data_1_ofc_0_01_seqlen2_normOFloss_OFonHR'

VALID_FIRST : True
