GPUS : '1'
PRINT_FREQ : 500
SAVE_EVERY_EPOCH : 10
ADD_TIMESTAMP : False

OUTPUT_DIR : '/cvlabdata2/home/davydov/videoHMR_SSL/output/finetune_hmr_ssl'

MODELS :
  hmrnet :
    DIR : 'hmr'
    ARCH : 'hmr'
    PARAMS :
      pretrained : True

LOSSES :
  shape_smooth :
    DIR : 'seq_optim'
    NAME : 'AvgSmoother'
    WEIGHT : 10.0
    PARAMS :
      kernel_size : 30
      data_consistency_w : 0.5
  j3d_smooth :
    DIR : 'seq_optim'
    NAME : 'AvgSmoother'
    WEIGHT : 10.0
    PARAMS :
      kernel_size : 30
      data_consistency_w : 0.5
  flow_2d :
    DIR : 'optical_flow'
    NAME : 'Flow2DLoss'
    WEIGHT : 0.003

  ### these are the trackers mostly
  pose2d :
    DIR : 'pose_eval'
    NAME : 'Keypoint2DPixelAlignment'
  mpjpe :
    DIR : 'pose_eval'
    NAME : 'MPJPE'
  pa_mpjpe :
    DIR : 'pose_eval'
    NAME : 'PAMPJPE'
  mpvpe :
    DIR : 'pose_eval'
    NAME : 'MPVPE'
  accel :
    DIR : 'pose_eval'
    NAME : 'Acceleration'
  accel_err :
    DIR : 'pose_eval'
    NAME : 'AccelerationError'

OPTIM :
  hmrnet :
    NAME : 'Adam'
    PARAMS :
      lr : 0.00001
      betas : [0.5, 0.999]
      weight_decay : 0

DATASETS :
  video_finetune :
    DIR : 'threedpw'
    NAME : 'ThreeDPW'
    PARAMS :
      set : "train"
      seqlen : 32
      debug : True
  valid :
    DIR : 'coco_eft'
    NAME : 'COCO_EFT'
    PARAMS :
        is_train : False
  eval :
    DIR : 'threedpw'
    NAME : 'ThreeDPW'
    PARAMS :
      set : "test"
      seqlen : 16
      debug : True

DATALOAD :
  video_finetune :
    NUM_ITERATIONS_PER_EPOCH : 2_000
    PARAMS :
      shuffle : True
      batch_size : 1
      num_workers : 8
  valid :
    PARAMS :
      shuffle : False
      batch_size : 32
      num_workers : 0
  eval :
    PARAMS :
      shuffle : False
      batch_size : 16
      num_workers : 8

TRAINING :
  END_EPOCH : 200
  RESUME :
    CKPT : "/cvlabdata2/home/davydov/videoHMR_SSL/output/train_hmr/train_hmr_coco_eft_basic_lr5e-5_no_sched_workers_16_3rd_try/best.pth" # hmr eft ours
    LOAD_MODELS_ONLY : True

PROCEDURE : 'finetune_hmr_ssl'

EXP_NAME : 'finetune_hmr_ssl__lr1e-5'

VALID_FIRST : True
